"""Evidence-first investment review data foundation.

The package stays read-only with respect to the existing portfolio ledger.  It
stores normalized review events, decision notes, and reviewed snapshots in a
separate SQLite database so later analysis remains traceable and reversible.
"""

from .models import CanonicalTradeEvent, DecisionRecord, SourceDefinition
from .episodes import (
    build_episode_collection,
    load_p2b_snapshot_references,
    query_episode_collection,
    validate_episode_collection,
)
from .episode_portfolio_context import (
    METRIC_REGISTRY_VERSION,
    SCHEMA_VERSION as EPISODE_PORTFOLIO_CONTEXT_SCHEMA_VERSION,
    VALIDATION_SCHEMA_VERSION as EPISODE_PORTFOLIO_CONTEXT_VALIDATION_SCHEMA_VERSION,
    EpisodePortfolioContextError,
    build_episode_portfolio_context,
    load_episode_portfolio_context,
    query_episode_portfolio_context,
    replay_validate_episode_portfolio_context,
    save_episode_portfolio_context,
    validate_episode_portfolio_context,
)
from .episode_review import (
    FACT_ENGINE_VERSION,
    SCHEMA_VERSION as EPISODE_REVIEW_SCHEMA_VERSION,
    VALIDATION_SCHEMA_VERSION as EPISODE_REVIEW_VALIDATION_SCHEMA_VERSION,
    EpisodeReviewError,
    build_facts_only_episode_review,
    load_episode_review,
    query_episode_review,
    render_episode_review_markdown,
    replay_validate_episode_review,
    save_episode_review,
    validate_episode_review,
)
from .episode_interpretation import (
    ATTEMPT_SCHEMA_VERSION as INTERPRETATION_ATTEMPT_SCHEMA_VERSION,
    INTERPRETATION_ENGINE_VERSION,
    OUTPUT_SCHEMA_VERSION as INTERPRETATION_OUTPUT_SCHEMA_VERSION,
    PROMPT_TEMPLATE_ID as INTERPRETATION_PROMPT_TEMPLATE_ID,
    InterpretationBuildResult,
    InterpretationError,
    InterpretationOutputError,
    RecordedResponseProvider,
    UnavailableInterpretationProvider,
    build_interpretation_prompt,
    build_model_assisted_episode_review,
    replay_validate_interpretation_attempt,
    save_interpretation_attempt,
    validate_interpretation_attempt,
)
from .episode_revision import (
    CHAIN_VALIDATION_SCHEMA_VERSION as EPISODE_REVISION_CHAIN_VALIDATION_SCHEMA_VERSION,
    DIFF_SCHEMA_VERSION as EPISODE_REVIEW_DIFF_SCHEMA_VERSION,
    REQUEST_SCHEMA_VERSION as HUMAN_REVIEW_REQUEST_SCHEMA_VERSION,
    REQUEST_VALIDATION_SCHEMA_VERSION as HUMAN_REVIEW_REQUEST_VALIDATION_SCHEMA_VERSION,
    EpisodeRevisionError,
    apply_human_review,
    diff_episode_reviews,
    list_episode_review_revisions,
    load_human_review_request,
    query_episode_review_revision,
    save_new_episode_review,
    validate_human_review_request,
    validate_revision_chain,
)
from .portfolio_context import (
    PORTFOLIO_METRIC_METHOD_REGISTRY,
    PORTFOLIO_METRIC_REGISTRY_VERSION,
    MetricEvidence,
    PortfolioContext,
    PortfolioMetric,
    PortfolioSnapshot,
    PortfolioWarning,
    PositionSnapshot,
    calculate_portfolio_evidence_metrics,
    calculate_portfolio_metrics,
    deterministic_portfolio_evidence_json,
    portfolio_metric_method_ref,
)
from .review_input_bundle import (
    SCHEMA_VERSION as REVIEW_INPUT_BUNDLE_SCHEMA_VERSION,
    VALIDATION_SCHEMA_VERSION as REVIEW_INPUT_BUNDLE_VALIDATION_SCHEMA_VERSION,
    ReviewInputBundleError,
    build_review_input_bundle,
    load_review_input_bundle,
    query_review_input_bundle,
    replay_validate_review_input_bundle,
    save_review_input_bundle,
    validate_review_input_bundle,
)
from .store import DataConflictError, ReviewStore

__all__ = [
    "CanonicalTradeEvent",
    "DataConflictError",
    "DecisionRecord",
    "EPISODE_PORTFOLIO_CONTEXT_SCHEMA_VERSION",
    "EPISODE_PORTFOLIO_CONTEXT_VALIDATION_SCHEMA_VERSION",
    "EPISODE_REVIEW_SCHEMA_VERSION",
    "EPISODE_REVIEW_VALIDATION_SCHEMA_VERSION",
    "EPISODE_REVISION_CHAIN_VALIDATION_SCHEMA_VERSION",
    "EPISODE_REVIEW_DIFF_SCHEMA_VERSION",
    "HUMAN_REVIEW_REQUEST_SCHEMA_VERSION",
    "HUMAN_REVIEW_REQUEST_VALIDATION_SCHEMA_VERSION",
    "EpisodeRevisionError",
    "EpisodeReviewError",
    "FACT_ENGINE_VERSION",
    "INTERPRETATION_ATTEMPT_SCHEMA_VERSION",
    "INTERPRETATION_ENGINE_VERSION",
    "INTERPRETATION_OUTPUT_SCHEMA_VERSION",
    "INTERPRETATION_PROMPT_TEMPLATE_ID",
    "InterpretationBuildResult",
    "InterpretationError",
    "InterpretationOutputError",
    "EpisodePortfolioContextError",
    "MetricEvidence",
    "METRIC_REGISTRY_VERSION",
    "PORTFOLIO_METRIC_METHOD_REGISTRY",
    "PORTFOLIO_METRIC_REGISTRY_VERSION",
    "PortfolioContext",
    "PortfolioMetric",
    "PortfolioSnapshot",
    "PortfolioWarning",
    "PositionSnapshot",
    "ReviewStore",
    "REVIEW_INPUT_BUNDLE_SCHEMA_VERSION",
    "REVIEW_INPUT_BUNDLE_VALIDATION_SCHEMA_VERSION",
    "ReviewInputBundleError",
    "SourceDefinition",
    "RecordedResponseProvider",
    "UnavailableInterpretationProvider",
    "build_interpretation_prompt",
    "build_model_assisted_episode_review",
    "apply_human_review",
    "build_episode_collection",
    "build_episode_portfolio_context",
    "build_facts_only_episode_review",
    "build_review_input_bundle",
    "calculate_portfolio_evidence_metrics",
    "calculate_portfolio_metrics",
    "deterministic_portfolio_evidence_json",
    "diff_episode_reviews",
    "list_episode_review_revisions",
    "load_p2b_snapshot_references",
    "load_episode_portfolio_context",
    "load_episode_review",
    "load_human_review_request",
    "load_review_input_bundle",
    "portfolio_metric_method_ref",
    "query_episode_portfolio_context",
    "query_episode_review",
    "query_episode_review_revision",
    "query_review_input_bundle",
    "replay_validate_episode_portfolio_context",
    "replay_validate_episode_review",
    "replay_validate_interpretation_attempt",
    "replay_validate_review_input_bundle",
    "query_episode_collection",
    "save_episode_portfolio_context",
    "save_episode_review",
    "save_new_episode_review",
    "save_interpretation_attempt",
    "save_review_input_bundle",
    "validate_episode_portfolio_context",
    "validate_episode_review",
    "validate_human_review_request",
    "validate_interpretation_attempt",
    "validate_review_input_bundle",
    "validate_revision_chain",
    "validate_episode_collection",
    "render_episode_review_markdown",
]

__version__ = "0.4.0"
