from __future__ import annotations

import csv
import re
import sys
from pathlib import Path
from typing import Mapping

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from evidence_io import (  # noqa: E402
    CLAIM_CANDIDATE_FIELDNAMES,
    METRIC_CANDIDATE_FIELDNAMES,
    hash_json,
    safe_slug,
    short_hash,
    utc_now_iso,
)


CLAIM_KEYWORDS = (
    "数据中心",
    "智算中心",
    "液冷",
    "温控",
    "热管理",
    "机房",
    "算力",
    "风险",
)

METRIC_KEYWORDS = {
    "营业收入": "revenue_statement",
    "净利润": "net_profit_statement",
    "毛利率": "gross_margin_statement",
    "现金流": "cashflow_statement",
}


def load_page_map(path: Path) -> list[dict[str, object]]:
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) if path.exists() else []
    if isinstance(payload, dict):
        payload = payload.get("pages", [])
    return list(payload or [])


def _read_manifest_row(manifest_row: Mapping[str, str] | None) -> dict[str, str]:
    row = dict(manifest_row or {})
    return {
        "evidence_id": row.get("evidence_id", ""),
        "source_type": row.get("source_type", "annual_report"),
        "source_name": row.get("source_name", "unknown_source"),
        "reliability_rank": row.get("reliability_rank", "A"),
        "entity_type": row.get("entity_type", "company"),
        "entity_id": row.get("entity_id", row.get("company_id", "")),
        "segment_id": row.get("segment_id", ""),
        "company_id": row.get("company_id", row.get("entity_id", "")),
        "stock_code": row.get("stock_code", ""),
    }


def _excerpt(text: str, keyword: str, radius: int = 80) -> str:
    index = text.find(keyword)
    if index < 0:
        return text.strip()[:180]
    start = max(0, index - radius)
    end = min(len(text), index + len(keyword) + radius)
    return re.sub(r"\s+", " ", text[start:end]).strip()


def generate_claim_candidates(
    *,
    pages: list[dict[str, object]],
    manifest_row: Mapping[str, str] | None,
) -> list[dict[str, str]]:
    meta = _read_manifest_row(manifest_row)
    evidence_id = meta["evidence_id"]
    created_at = utc_now_iso()
    candidates: list[dict[str, str]] = []
    seen: set[tuple[str, int]] = set()
    for page in pages:
        text = str(page.get("text", ""))
        page_no = int(page.get("page_no", 0) or 0)
        for keyword in CLAIM_KEYWORDS:
            if keyword not in text or (keyword, page_no) in seen:
                continue
            seen.add((keyword, page_no))
            claim_type = "risk" if keyword == "风险" else "fact"
            materiality = "material" if keyword in {"数据中心", "智算中心", "液冷", "热管理"} else "supporting"
            digest = short_hash(hash_json([evidence_id, keyword, page_no, text[:120]]), 8)
            claim_text = (
                f"年报披露公司业务或产品与“{keyword}”相关，"
                "该表述可作为业务/产品暴露候选，收入占比仍需单独披露。"
            )
            if keyword == "风险":
                claim_text = "年报披露的风险因素应进入后续反证和跟踪清单。"
            candidates.append(
                {
                    "claim_candidate_id": f"claimcand_{safe_slug(keyword)}_{digest}",
                    "evidence_id": evidence_id,
                    "source_type": meta["source_type"],
                    "source_name": meta["source_name"],
                    "reliability_rank": meta["reliability_rank"],
                    "entity_type": meta["entity_type"],
                    "entity_id": meta["entity_id"],
                    "segment_id": meta["segment_id"],
                    "company_id": meta["company_id"],
                    "stock_code": meta["stock_code"],
                    "claim_text": claim_text,
                    "claim_type": claim_type,
                    "claim_scope": "business_exposure" if materiality == "material" else "risk_or_context",
                    "quote_or_excerpt": _excerpt(text, keyword),
                    "page_no_or_section": f"page:{page_no}",
                    "table_id": "",
                    "confidence": "medium",
                    "materiality": materiality,
                    "support_level": "direct_excerpt",
                    "needs_review_reason": "annual_report_locator_extracted",
                    "review_status": "draft",
                    "promote_to_claim_id": "",
                    "created_at": created_at,
                    "notes": "Generated by evidence-ingest candidate extractor; not a final conclusion.",
                }
            )
    return candidates


def generate_metric_candidates(
    *,
    pages: list[dict[str, object]],
    manifest_row: Mapping[str, str] | None,
) -> list[dict[str, str]]:
    meta = _read_manifest_row(manifest_row)
    evidence_id = meta["evidence_id"]
    created_at = utc_now_iso()
    candidates: list[dict[str, str]] = []
    for page in pages:
        text = str(page.get("text", ""))
        page_no = int(page.get("page_no", 0) or 0)
        for keyword, metric_name in METRIC_KEYWORDS.items():
            if keyword not in text:
                continue
            excerpt = _excerpt(text, keyword, radius=100)
            digest = short_hash(hash_json([evidence_id, metric_name, page_no, excerpt]), 8)
            candidates.append(
                {
                    "metric_candidate_id": f"metriccand_{safe_slug(metric_name)}_{digest}",
                    "source_evidence_id": evidence_id,
                    "source_name": meta["source_name"],
                    "source_type": meta["source_type"],
                    "entity_type": meta["entity_type"],
                    "entity_id": meta["entity_id"],
                    "segment_id": meta["segment_id"],
                    "company_id": meta["company_id"],
                    "stock_code": meta["stock_code"],
                    "metric_name": metric_name,
                    "metric_category": "annual_report_text_statement",
                    "period": "MISSING_DISCLOSURE",
                    "period_type": "annual",
                    "value": "MISSING_DISCLOSURE",
                    "unit": "MISSING_DISCLOSURE",
                    "currency": "",
                    "original_value_text": excerpt,
                    "original_unit_text": "MISSING_DISCLOSURE",
                    "table_id": "",
                    "page_no_or_section": f"page:{page_no}",
                    "calculation_method": "text_locator_only_no_numeric_normalization",
                    "is_estimate": "false",
                    "is_reported": "true",
                    "confidence": "low",
                    "review_status": "draft",
                    "promote_to_metric_id": "",
                    "created_at": created_at,
                    "notes": "Text statement candidate; numeric value remains missing until table review.",
                }
            )
    return candidates


def write_candidates(
    *,
    claim_path: Path,
    metric_path: Path,
    claim_rows: list[dict[str, str]],
    metric_rows: list[dict[str, str]],
) -> None:
    claim_path.parent.mkdir(parents=True, exist_ok=True)
    metric_path.parent.mkdir(parents=True, exist_ok=True)
    with claim_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=CLAIM_CANDIDATE_FIELDNAMES, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(claim_rows)
    with metric_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=METRIC_CANDIDATE_FIELDNAMES, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(metric_rows)


def extract_candidates_from_page_map(
    *,
    page_map_path: Path,
    manifest_row: Mapping[str, str] | None,
    output_dir: Path,
) -> dict[str, object]:
    pages = load_page_map(page_map_path)
    evidence_id = _read_manifest_row(manifest_row)["evidence_id"]
    claim_rows = generate_claim_candidates(pages=pages, manifest_row=manifest_row)
    metric_rows = generate_metric_candidates(pages=pages, manifest_row=manifest_row)
    claim_path = output_dir / f"claim_candidates_{evidence_id}.csv"
    metric_path = output_dir / f"metric_candidates_{evidence_id}.csv"
    write_candidates(
        claim_path=claim_path,
        metric_path=metric_path,
        claim_rows=claim_rows,
        metric_rows=metric_rows,
    )
    return {
        "claim_candidates_path": str(claim_path),
        "metric_candidates_path": str(metric_path),
        "claim_candidates": len(claim_rows),
        "metric_candidates": len(metric_rows),
    }
