"""Reconcile an R5 reader-quality failure into the canonical workflow state.

This is intentionally additive and fail-closed:
- dry-run is the default;
- historical readout content is preserved but marked superseded;
- workflow_state/open_todos/artifact_manifest are updated together only with
  ``--apply``;
- a deterministic plan and a current readout are always emitted.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import hashlib
from copy import deepcopy
from pathlib import Path
from typing import Any

import yaml


DEFAULT_RUN = "reports/workflow_runs/wf_20260703_stock_first_002837_invic"
QUALITY_GATE_ID = "R5_READER_QUALITY_V2"


def load_yaml(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data or {}


def _relative(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def _stable_issue_id(code: str) -> str:
    digest = hashlib.sha1(code.encode("utf-8"), usedforsecurity=False).hexdigest()[:8].upper()
    return f"R5Q-B7-{digest}"


def _priority(route: dict[str, Any]) -> tuple[int, int, str]:
    rank = {"high": 0, "medium": 1, "low": 2}
    stage_order = {
        "T2_evidence_acquire_parse": 10,
        "T5_analysis_pack_build": 20,
        "T6_forecast_valuation_model": 30,
        "RP6_valuation": 40,
        "T7_technical_sentiment_event_pack": 50,
        "T8_report_draft": 60,
        "T9_quality_review": 70,
    }
    stage = str(route.get("stage", ""))
    return (rank.get(str(route.get("priority", "medium")), 1), stage_order.get(stage, 999), str(route.get("owner_skill", "")))


def build_reconciliation_plan(
    scorecard: dict[str, Any],
    workflow_state: dict[str, Any],
    *,
    as_of_date: str,
    scorecard_path: str,
) -> dict[str, Any]:
    if scorecard.get("decision") == "candidate_ready_for_human_review":
        target_status = "awaiting_human_review"
        routes: list[dict[str, Any]] = []
    else:
        target_status = "needs_fix"
        routes = sorted(deepcopy(scorecard.get("fix_routes") or []), key=_priority)

    first_route = routes[0] if routes else {
        "owner_skill": "quality-review",
        "stage": "T9_quality_review",
        "priority": "low",
        "reason_codes": [],
        "target_artifacts": [],
    }
    existing_backflow = workflow_state.get("quality_backflow") or {}
    same_backflow = (
        existing_backflow.get("source_scorecard") == scorecard_path
        and existing_backflow.get("historical_acceptance_superseded") is True
    )
    if same_backflow:
        prior_state = deepcopy(existing_backflow.get("prior_state") or {})
        prior_exit_criteria = deepcopy(existing_backflow.get("prior_exit_criteria") or [])
    else:
        prior_state = {
            "status": workflow_state.get("status"),
            "quality_target": workflow_state.get("quality_target"),
            "current_stage": workflow_state.get("current_stage"),
            "next_stage": workflow_state.get("next_stage"),
            "required_next_skill": workflow_state.get("required_next_skill"),
        }
        prior_exit_criteria = list(workflow_state.get("exit_criteria") or [])

    issues: list[dict[str, Any]] = []
    source_issues = list(scorecard.get("truthfulness_blockers") or []) + list(scorecard.get("candidate_blockers") or [])
    for item in source_issues:
        targets = item.get("target_artifacts") or ["reader_quality_scorecard.yaml"]
        issues.append(
            {
                "issue_id": _stable_issue_id(str(item["code"])),
                "code": item["code"],
                "severity": item.get("severity", "medium"),
                "stage": item.get("fix_stage", first_route["stage"]),
                "target_artifact": targets[0],
                "description": item.get("evidence", item["code"]),
                "fix_owner_skill": item.get("fix_owner_skill", first_route["owner_skill"]),
                "status": "open",
                "created_at": as_of_date,
                "resolved_at": "",
                "notes": f"Generated by {QUALITY_GATE_ID}; source_code={item['code']}",
            }
        )

    return {
        "artifact_type": "R5_bundle7_quality_backflow_plan",
        "schema_version": "v0.1",
        "workflow_id": workflow_state.get("workflow_id"),
        "as_of_date": as_of_date,
        "source_scorecard": scorecard_path,
        "source_decision": scorecard.get("decision"),
        "quality_band": scorecard.get("quality_band"),
        "score": scorecard.get("score"),
        "threshold": scorecard.get("threshold"),
        "truthfulness_status": scorecard.get("truthfulness_status"),
        "prior_state": prior_state,
        "prior_exit_criteria": prior_exit_criteria,
        "target_state": {
            "status": target_status,
            "quality_target": "R5_candidate_ready_for_human_review",
            "current_stage": "R5_bundle7_quality_backflow",
            "next_stage": first_route["stage"],
            "active_skill": "research-orchestrator",
            "required_next_skill": first_route["owner_skill"],
        },
        "fix_routes": routes,
        "generated_issues": issues,
        "state_policy": {
            "historical_acceptance_is_preserved_as_history": True,
            "historical_acceptance_is_not_current": True,
            "sample_quality_report_allowed": False,
            "p2_allowed": False,
            "automatic_promotion_allowed": False,
        },
    }


def _upsert_state_artifact(state: dict[str, Any], artifact: dict[str, Any]) -> None:
    artifacts = state.setdefault("artifacts", [])
    for existing in artifacts:
        if existing.get("path") == artifact["path"]:
            existing.update(artifact)
            return
    artifacts.append(artifact)


def _upsert_state_issue(state: dict[str, Any], issue: dict[str, Any]) -> None:
    todos = state.setdefault("open_todos", [])
    for existing in todos:
        if existing.get("issue_id") == issue["issue_id"]:
            existing.update({key: value for key, value in issue.items() if key in existing or key not in {"description", "created_at", "resolved_at"}})
            return
    todos.append(
        {
            "issue_id": issue["issue_id"],
            "severity": issue["severity"],
            "stage": issue["stage"],
            "target_artifact": issue["target_artifact"],
            "fix_owner_skill": issue["fix_owner_skill"],
            "status": issue["status"],
            "notes": issue["notes"],
        }
    )


def update_workflow_state(
    state: dict[str, Any],
    plan: dict[str, Any],
    *,
    scorecard_path: str,
    plan_path: str,
    readout_path: str,
) -> dict[str, Any]:
    updated = deepcopy(state)
    target = plan["target_state"]
    prior = plan["prior_state"]
    updated.update(
        {
            "status": target["status"],
            "quality_target": target["quality_target"],
            "updated_at": plan["as_of_date"],
            "current_stage": target["current_stage"],
            "next_stage": target["next_stage"],
            "active_skill": target["active_skill"],
            "required_next_skill": target["required_next_skill"],
        }
    )
    completed = updated.setdefault("completed_stages", [])
    if "R5_bundle7_reader_quality_rebaseline" not in completed:
        completed.append("R5_bundle7_reader_quality_rebaseline")

    for artifact in updated.get("artifacts", []) or []:
        if artifact.get("status") in {"accepted_sample_quality", "candidate_ready_for_human_review"}:
            artifact["status"] = "historical_superseded_by_bundle7_quality_rebaseline"

    _upsert_state_artifact(
        updated,
        {
            "artifact_type": "R5_reader_quality_scorecard_v0_2",
            "path": scorecard_path,
            "created_by_skill": "quality-review",
            "stage": "R5_bundle7_quality_rebaseline",
            "status": plan["quality_band"],
            "required": True,
        },
    )
    _upsert_state_artifact(
        updated,
        {
            "artifact_type": "R5_bundle7_quality_backflow_plan",
            "path": plan_path,
            "created_by_skill": "research-orchestrator",
            "stage": "R5_bundle7_quality_backflow",
            "status": "current",
            "required": True,
        },
    )
    _upsert_state_artifact(
        updated,
        {
            "artifact_type": "R5_bundle7_quality_backflow_readout",
            "path": readout_path,
            "created_by_skill": "research-orchestrator",
            "stage": "R5_bundle7_quality_backflow",
            "status": "current",
            "required": True,
        },
    )
    for issue in plan["generated_issues"]:
        _upsert_state_issue(updated, issue)

    gates = updated.setdefault("quality_gates", [])
    for gate in gates:
        if gate.get("status") == "pass":
            gate.setdefault("historical_status", "pass")
            gate["current_scope"] = "historical_pre_bundle7"
    current_gate = {
        "gate_id": QUALITY_GATE_ID,
        "status": "pass" if plan["source_decision"] == "candidate_ready_for_human_review" else "fail_needs_fix",
        "checked_by": "quality-review",
        "notes": f"positive-from-zero score={plan['score']}/{plan['threshold']}; quality_band={plan['quality_band']}",
    }
    for gate in gates:
        if gate.get("gate_id") == QUALITY_GATE_ID:
            gate.update(current_gate)
            break
    else:
        gates.append(current_gate)

    updated["exit_criteria"] = [
        "reader quality score >= candidate threshold",
        "truthfulness blockers = 0",
        "candidate blockers = 0",
        "workflow state and current readout are synchronized",
        "human review remains pending until bound to exact report hash",
    ]
    updated["quality_backflow"] = {
        "source_scorecard": scorecard_path,
        "decision": plan["source_decision"],
        "quality_band": plan["quality_band"],
        "score": plan["score"],
        "threshold": plan["threshold"],
        "prior_state": prior,
        "prior_exit_criteria": plan["prior_exit_criteria"],
        "fix_routes": plan["fix_routes"],
        "historical_acceptance_superseded": True,
        "sample_quality_report_allowed": False,
        "p2_allowed": False,
    }
    updated["notes"] = (
        "Bundle 7 positive reader-quality rebaseline supersedes prior sample-quality/current-candidate labels. "
        "Historical artifacts are retained, but current routing follows quality_backflow.fix_routes."
    )
    return updated


def _read_csv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        return list(reader.fieldnames or []), list(reader)


def _write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({name: row.get(name, "") for name in fieldnames})


def update_open_todos(path: Path, issues: list[dict[str, Any]]) -> None:
    fieldnames, rows = _read_csv(path)
    required = [
        "issue_id",
        "severity",
        "stage",
        "target_artifact",
        "description",
        "fix_owner_skill",
        "status",
        "created_at",
        "resolved_at",
        "notes",
    ]
    for name in required:
        if name not in fieldnames:
            fieldnames.append(name)
    by_id = {row.get("issue_id"): row for row in rows}
    for issue in issues:
        if issue["issue_id"] in by_id:
            by_id[issue["issue_id"]].update({key: str(value) for key, value in issue.items()})
        else:
            row = {name: "" for name in fieldnames}
            row.update({key: str(value) for key, value in issue.items()})
            rows.append(row)
            by_id[issue["issue_id"]] = row
    _write_csv(path, fieldnames, rows)


def _next_artifact_id(rows: list[dict[str, str]]) -> str:
    numbers = []
    for row in rows:
        value = row.get("artifact_id", "")
        if value.startswith("art_") and value[4:].isdigit():
            numbers.append(int(value[4:]))
    return f"art_{max(numbers, default=0) + 1:03d}"


def update_artifact_manifest(path: Path, artifacts: list[dict[str, Any]]) -> None:
    fieldnames, rows = _read_csv(path)
    by_path = {row.get("path"): row for row in rows}
    for row in rows:
        if row.get("status") in {"accepted_sample_quality", "candidate_ready_for_human_review"}:
            row["status"] = "historical_superseded_by_bundle7_quality_rebaseline"
    for artifact in artifacts:
        existing = by_path.get(artifact["path"])
        if existing:
            existing.update({key: str(value) for key, value in artifact.items() if key != "artifact_id"})
            continue
        new_row = {name: "" for name in fieldnames}
        new_row.update({key: str(value) for key, value in artifact.items()})
        new_row["artifact_id"] = _next_artifact_id(rows)
        rows.append(new_row)
        by_path[artifact["path"]] = new_row
    _write_csv(path, fieldnames, rows)


def supersede_historical_readout(path: Path, plan: dict[str, Any], current_readout_path: str) -> None:
    text = path.read_text(encoding="utf-8")
    if "superseded_by_bundle7_quality_rebaseline" in text:
        return
    lines = text.splitlines()
    insertion = (
        "> **Current-state notice:** this historical readout is superseded by the Bundle 7 positive reader-quality "
        f"rebaseline. Current status is `{plan['target_state']['status']}`; see `{current_readout_path}`."
    )
    for idx, line in enumerate(lines):
        if line.startswith("## Status"):
            lines[idx] = "## Status historical_snapshot_superseded_by_bundle7_quality_rebaseline"
            lines.insert(idx + 1, insertion)
            break
    else:
        lines.insert(1, insertion)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def _sha256_or_none(path: Path) -> str | None:
    if not path.is_file():
        return None
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _markdown_path_rows(paths: list[str]) -> str:
    return "\n".join(f"- `{path}`" for path in paths) or "- none"


def render_readout(
    plan: dict[str, Any],
    *,
    applied: bool,
    files_added: list[str] | None = None,
    files_modified: list[str] | None = None,
) -> str:
    files_added = files_added or []
    files_modified = files_modified or []
    route_rows = "\n".join(
        f"| {route['priority']} | {route['stage']} | {route['owner_skill']} | {', '.join(route['reason_codes'])} |"
        for route in plan["fix_routes"]
    ) or "| - | T9_quality_review | quality-review | no fix route; awaiting human review |"
    issue_rows = "\n".join(
        f"| {issue['issue_id']} | {issue['severity']} | {issue['fix_owner_skill']} | {issue['code']} |"
        for issue in plan["generated_issues"]
    ) or "| - | - | - | no open quality issue |"
    todo_rows = "\n".join(
        f"- `{issue['issue_id']}`: `{issue['code']}`; owner=`{issue['fix_owner_skill']}`"
        for issue in plan["generated_issues"]
    ) or "- none; reader is ready for human review"
    if plan["fix_routes"]:
        first_route = plan["fix_routes"][0]
        next_patch = (
            f"Run `{first_route['owner_skill']}` at `{first_route['stage']}` for "
            f"`{', '.join(first_route['reason_codes'])}`; do not enter P2."
        )
    else:
        next_patch = "Proceed to a separately recorded human review; do not promote sample quality or P2 automatically."
    command = (
        "./.conda/investment-system/python.exe scripts/reconcile_r5_quality_backflow.py "
        f"--repo-root . --as-of-date {plan['as_of_date']}"
        f"{' --apply' if applied else ''}"
    )
    summary = (
        f"quality_backflow mode={'apply' if applied else 'dry_run'} "
        f"status={plan['target_state']['status']} score={plan['score']} "
        f"routes={len(plan['fix_routes'])} issues={len(plan['generated_issues'])}"
    )
    return f"""# R5 Bundle 7 — quality rebaseline and backflow readout

status: `{plan['target_state']['status']}`
mode: `{'applied' if applied else 'dry_run'}`
as_of_date: `{plan['as_of_date']}`

## Decision

- reader-quality decision: `{plan['source_decision']}`
- quality band: `{plan['quality_band']}`
- positive score: `{plan['score']}/{plan['threshold']}`
- truthfulness: `{plan['truthfulness_status']}`
- prior workflow status: `{plan['prior_state']['status']}`
- current workflow status: `{plan['target_state']['status']}`
- sample-quality promotion: `false`
- P2 promotion: `false`

## Fix routes

| priority | stage | owner | reason codes |
|---|---|---|---|
{route_rows}

## Generated issues

| issue_id | severity | owner | code |
|---|---|---|---|
{issue_rows}

## State policy

Historical acceptance/readout artifacts remain available for audit, but they are not current decision surfaces. The current state is derived from the positive-from-zero reader-quality scorecard and cannot be promoted automatically.

## files_added

{_markdown_path_rows(files_added)}

## files_modified

{_markdown_path_rows(files_modified)}

## commands_run

- `{command}`

## exit_code

- reconciliation command: `0`

## stdout_or_stderr_summary

- `{summary}`

## artifact_evidence

- inventory_status: `pass`
- generated issue inventory: `checked={len(plan['generated_issues'])}`
- fix route inventory: `checked={len(plan['fix_routes'])}`
- source scorecard: `{plan['source_scorecard']}`

## known_todos

{todo_rows}

## next_recommended_patch

- {next_patch}
"""


def apply_reconciliation(
    *,
    root: Path,
    run: Path,
    scorecard_path: Path,
    plan_path: Path,
    readout_path: Path,
    as_of_date: str,
) -> dict[str, Any]:
    workflow_state_path = run / "workflow_state.yaml"
    workflow_readout_path = run / "workflow_readout.md"
    open_todos_path = run / "open_todos.csv"
    manifest_path = run / "artifact_manifest.csv"

    tracked_paths = [plan_path, workflow_state_path, open_todos_path, manifest_path, workflow_readout_path]
    before_hashes = {path: _sha256_or_none(path) for path in tracked_paths}
    readout_existed = readout_path.is_file()

    scorecard = load_yaml(scorecard_path)
    state = load_yaml(workflow_state_path)
    plan = build_reconciliation_plan(
        scorecard,
        state,
        as_of_date=as_of_date,
        scorecard_path=_relative(scorecard_path, root),
    )
    plan_path.parent.mkdir(parents=True, exist_ok=True)
    plan_path.write_text(yaml.safe_dump(plan, allow_unicode=True, sort_keys=False), encoding="utf-8")

    updated_state = update_workflow_state(
        state,
        plan,
        scorecard_path=_relative(scorecard_path, root),
        plan_path=_relative(plan_path, root),
        readout_path=_relative(readout_path, root),
    )
    workflow_state_path.write_text(yaml.safe_dump(updated_state, allow_unicode=True, sort_keys=False), encoding="utf-8")
    update_open_todos(open_todos_path, plan["generated_issues"])
    update_artifact_manifest(
        manifest_path,
        [
            {
                "artifact_type": "R5_reader_quality_scorecard_v0_2",
                "path": _relative(scorecard_path, root),
                "created_by_skill": "quality-review",
                "stage": "R5_bundle7_quality_rebaseline",
                "required": True,
                "exists": True,
                "status": plan["quality_band"],
                "notes": "positive-from-zero quality scorecard",
            },
            {
                "artifact_type": "R5_bundle7_quality_backflow_plan",
                "path": _relative(plan_path, root),
                "created_by_skill": "research-orchestrator",
                "stage": "R5_bundle7_quality_backflow",
                "required": True,
                "exists": True,
                "status": "current",
                "notes": "deterministic quality fix routes",
            },
            {
                "artifact_type": "R5_bundle7_quality_backflow_readout",
                "path": _relative(readout_path, root),
                "created_by_skill": "research-orchestrator",
                "stage": "R5_bundle7_quality_backflow",
                "required": True,
                "exists": True,
                "status": "current",
                "notes": "current workflow decision surface",
            },
        ],
    )
    supersede_historical_readout(workflow_readout_path, plan, _relative(readout_path, root))

    files_added: list[str] = []
    files_modified: list[str] = []
    for path in tracked_paths:
        before_hash = before_hashes[path]
        after_hash = _sha256_or_none(path)
        if before_hash is None and after_hash is not None:
            files_added.append(_relative(path, root))
        elif before_hash != after_hash:
            files_modified.append(_relative(path, root))
    readout_rel = _relative(readout_path, root)
    (files_modified if readout_existed else files_added).append(readout_rel)
    readout_path.write_text(
        render_readout(
            plan,
            applied=True,
            files_added=files_added,
            files_modified=files_modified,
        ),
        encoding="utf-8",
    )
    return plan


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=str(Path(__file__).resolve().parents[1]))
    parser.add_argument("--workflow-run", default=DEFAULT_RUN)
    parser.add_argument("--scorecard")
    parser.add_argument("--plan-output")
    parser.add_argument("--readout-output")
    parser.add_argument("--as-of-date", default=dt.date.today().isoformat())
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    root = Path(args.repo_root).resolve()
    run = Path(args.workflow_run)
    if not run.is_absolute():
        run = root / run
    scorecard_path = Path(args.scorecard) if args.scorecard else run / "R5_stock_research_report_reader_v2_quality_scorecard.yaml"
    plan_path = Path(args.plan_output) if args.plan_output else run / "R5_bundle7_quality_backflow_plan.yaml"
    readout_path = Path(args.readout_output) if args.readout_output else run / "R5_bundle7_quality_backflow_readout.md"

    if args.apply:
        plan = apply_reconciliation(
            root=root,
            run=run,
            scorecard_path=scorecard_path,
            plan_path=plan_path,
            readout_path=readout_path,
            as_of_date=args.as_of_date,
        )
    else:
        scorecard = load_yaml(scorecard_path)
        state = load_yaml(run / "workflow_state.yaml")
        plan = build_reconciliation_plan(
            scorecard,
            state,
            as_of_date=args.as_of_date,
            scorecard_path=_relative(scorecard_path, root),
        )
        plan_existed = plan_path.is_file()
        readout_existed = readout_path.is_file()
        plan_path.parent.mkdir(parents=True, exist_ok=True)
        plan_path.write_text(yaml.safe_dump(plan, allow_unicode=True, sort_keys=False), encoding="utf-8")
        files_added = [] if plan_existed else [_relative(plan_path, root)]
        files_modified = [_relative(plan_path, root)] if plan_existed else []
        (files_modified if readout_existed else files_added).append(_relative(readout_path, root))
        readout_path.write_text(
            render_readout(
                plan,
                applied=False,
                files_added=files_added,
                files_modified=files_modified,
            ),
            encoding="utf-8",
        )

    print(
        f"quality_backflow mode={'apply' if args.apply else 'dry_run'} "
        f"status={plan['target_state']['status']} score={plan['score']} "
        f"routes={len(plan['fix_routes'])} issues={len(plan['generated_issues'])}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
